# Generated by Django 4.0.6 on 2022-07-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=200)),
                ('father', models.CharField(default='my_father', max_length=200)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
    ]
